# This workflow will verify the exercises in the repository.
#
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/verify-exercises

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      # TODO: setup any tooling that is required to run the tests.
      # E.g. install a specific version of a programming language
      # E.g. install packages via apt/apk/yum/etc.
      # - name: Use <setup tooling>
      #   uses: <action to setup tooling>

      # TODO: install any dependencies.
      # E.g. npm install, bundle install, etc.
      # - name: Install project dependencies
      #   run: <install dependencies>

      - name: Verify all exercises
        run: bin/verify-exercises
